unit Entity;

interface

uses
  SysUtils, StrUtils, Generics.Collections, System.TypInfo, Rtti,
  ZAbstractConnection, Data.DB, EntityAttributes;

type
  TEntity = class(TObject)
  private
    FID: Int64;
  public
    [Column('id', [cpPrimaryKey, cpUnique, cpNotNull, cpAutoGenerated])]
    property ID: Int64 read FID write FID;

    constructor Create; virtual;
  end;

implementation

constructor TEntity.Create;
begin
  inherited;
  //
end;

end.
