unit Entity;

interface

uses
  SysUtils, StrUtils, Classes, Generics.Collections, System.TypInfo, Rtti,
  ZAbstractConnection, Data.DB, EntityAttributes;

type
  TEntity = class(TObject)
  private
    FId: Int64;
  public
    [Column('id', [cpPrimaryKey, cpUnique, cpNotNull, cpAutoGenerated])]
    property Id: Int64 read FId write FId;

    constructor Create; virtual;

    function GetClassType: TClass;
  end;

implementation

constructor TEntity.Create;
begin
  inherited;
  //
end;

function TEntity.GetClassType: TClass;
begin
  Result := Self.ClassType;
end;

end.
